import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-white dark:bg-black border-b border-zinc-200 dark:border-zinc-800">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              <div className="flex-shrink-0">
                <h1 className="text-xl font-semibold text-black dark:text-zinc-50">
                  FlyRank Intern
                </h1>
              </div>
              <nav className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">
                  <Link
                    href="/dashboard"
                    className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                  >
                    Dashboard
                  </Link>
                  <Link
                    href="/profile"
                    className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                  >
                    Profile
                  </Link>
                  <Link
                    href="/onboarding"
                    className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                  >
                    Onboarding
                  </Link>
                  <Link
                    href="/progress"
                    className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                  >
                    Progress
                  </Link>
                  <Link
                    href="/health-check"
                    className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                  >
                    Health Check
                  </Link>
                </div>
              </nav>
              <div className="md:hidden">
                <button className="text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-50 p-2">
                  <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </header>
        {children}
        <footer className="bg-white dark:bg-black border-t border-zinc-200 dark:border-zinc-800 mt-auto">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <p className="text-center text-sm text-zinc-600 dark:text-zinc-400">
              © 2026 FlyRank Intern. Foundations Assignment
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
